version: '3'
services:
  registry:
    container_name: registry
    build: ./backend
    image: helm-registry
    command: /app/main
    ports:
      - "8080:8080"
    networks:
      - helm-net
    volumes:
      - ./backend:/go/src/app

  testcontainer:
    container_name: testcontainer
    image: idukelu/helm:latest
    command: >
      sh -c "./test/tests.sh"
    tty: true
    networks:
      - helm-net
    volumes:
      - ./test:/test

networks:
  helm-net:
    name: helm-net
    driver: bridge
