name: CI - Integration tests

on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:

env:
  TEST_IMAGE: idukelu/helm:latest
  REGISTRY_URL: http://127.0.0.1:50586

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
       
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: docker-compose.yml
          test-container: testcontainer
