name: CI - Integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TEST_IMAGE: idukelu/helm:latest
  REGISTRY_URL: http://regitry:8080

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Build application image (tag: test)
    - name: Build application image
      working-directory: backend
      run: docker build . --tag helm-registry:test

    # Pull test image
    - name: Pull test image
      run: docker pull ${{env.TEST_IMAGE}}

  run-test:
    name: Run Docker containers
    runs-on: ubuntu-latest
    services:
      # App container
      registry:
        image: registry:test
        ports:
          - 8080:8080
        options: --name registry

      # Test container
      testcontainer:
        image: ${{github.env.TEST_IMAGE}}
        options: --name testcontainer

  # Tests
  test:
    name: Run integration tests
    runs-on: ubuntu-latest
    steps:
    # Test 1 - Repo add
    - name: Test 1 - Repo add
      run: docker exec -it testcontainer helm add ${{env.REGISTRY_URL}}
  