name: CI - Integration tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TEST_IMAGE: idukelu/helm:latest
  REGISTRY_URL: http://regitry:8080

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build application Docker imahe
        uses: docker/build-push-action@v3
        with:
          context: backend
          push: false
          image-name: registry
          tags: test
  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run app container
        uses: docker/run-action@v3
        with:
          image: registry
          tag: test
          name: registry
          options: -p 8080:8080
          ports: 8080
      - name: Run test container
        uses: docker/run-action@v3
        with:
          image: ${{ env.TEST_IMAGE }}
          name: testcontainer
  test:
    needs: run
    runs-on: ubuntu-latest
    steps:
      - name: Execute command
        uses: docker/run-action@v3
        with:
          image: registry:latest
          command: "echo 'Hello, world!'"
