# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # Run API
    - name: Run
      run: go run -v ./backend
      env:
        CGO_ENABLED: 1
        REPOSITORY_DIR: ../test/chart
   
    - name: Wait for API to start
      run: sleep 5
      
    - name: Test
      run: go test -v ./test
      env:
        CGO_ENABLED: 1
